language: node_js
node_js:
  - '8'
services:
  - mongodb
  - rabbitmq
cache:
  directories:
  - $HOME/.npm
sudo: required
deploy:
  provider: npm
  email: kozzztya@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
